import Head from 'next/head';
import content from '../static/content.yaml';
import Section from '@/components/Section';
import Header from '@/components/Header';
import HomeContent from '@/components/HomeContent';
import SkillsContent from '@/components/SkillsContent';
import { useContentScrollContext } from '@/providers/ContentScrollProvider';

const { career, docTitle, header, home, projects, skills } = content;

export default function Home() {
  const { section } = useContentScrollContext();

  return (
    <>
      <Head>
        <title>{docTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header logo={header.logo} navItems={header.navItems} />
      <main className={section}>
        <Section title={home.title}>
          <HomeContent content={home.content} />
        </Section>
        <Section title={skills.title}>
          <SkillsContent content={skills.items} />
        </Section>
        <Section title={projects.title}>Projects content...</Section>
        <Section title={career.title}>Career content...</Section>
      </main>
    </>
  );
}
